# Generated by Django 4.2.17 on 2024-12-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_alter_wrapper_options_icecream_output_order_and_more'),
        ('ice_cream', '0005_auto_20230131_1130'),
    ]

    operations = [
    ]
