# Generated by Django 4.2.17 on 2024-12-26 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0006_merge_20241224_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('output_order',), 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': 'топпинг', 'verbose_name_plural': 'Топпинги'},
        ),
        migrations.AlterModelOptions(
            name='wrapper',
            options={'verbose_name': 'обёртка', 'verbose_name_plural': 'Обёртки'},
        ),
    ]
